services:
  - type: web
    name: canteen-management-system
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: PORT
        value: 10000
